fos_http_cache:
  cache_control:
    defaults:
      overwrite: true
    rules:
      -
        match:
          path: ^/css/*.css$
        headers:
          cache_control: { public: true, max_age: A1209600, s_maxage: A1209600 }
          last_modified: "-1 hour"
          etag: false
          vary: [Accept-Encoding, Accept-Language]
      -
        match:
          attributes: { _controller: ^App\\Controller\\CachedEntityExpireController::.* }
        headers:
          cache_control: { public: true, max_age: 15, s_maxage: 30 }
          last_modified: "-1 hour"
          vary: [Accept-Encoding, Accept-Language]
      -
        match:
          attributes: { _controller: ^App\\Controller\\CachedEntityValidationController::.* }
        headers:
          cache_control: { public: true }
          etag: true
          vary: [Accept-Encoding, Accept-Language]
      -
        match:
          attributes: { _controller: ^App\\Controller\\CachedEntityController::.* }
        headers:
          cache_control: { public: true }
          etag: true
          vary: [Accept-Encoding, Accept-Language]