<?php

namespace App\Repository;

/**
 * CachedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CachedEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
